### PR TITLE
fix: transfer panel format changed to FIL

### LINKED ISSUE #117: In Transfer panel, "Amount" field should be "FIL" not "AttoFIL"
CleanShot 2022-01-21 at 14 25 59@2x

### PR DESCRIPTION
**Pull request by irubido**
Closes #117

### CODE REVIEW

File: packages/example/src/components/Transfer/Transfer.tsx [hunk 1]
```diff
@@ -125,27 +126,27 @@ export const Transfer: React.FC<ITransferProps> = ({network, api, onNewMessageCa
...
                         <Box m="0.5rem"/>
                         <TextField
-                            InputProps={{startAdornment: <InputAdornment position="start">{`AttoFIL`}</InputAdornment>}}
+                            InputProps={{startAdornment: <InputAdornment position="start">{`FIL`}</InputAdornment>}}
                             onChange={handleGasFeeCapChange} size="medium" fullWidth id="gasfeecap" label="Gas Fee Cap" variant="outlined" value={gasFeeCap}>
                         </TextField>
                         <Box m="0.5rem"/>
                         <TextField
-                            InputProps={{startAdornment: <InputAdornment position="start">{`AttoFIL`}</InputAdornment>}}
+                            InputProps={{startAdornment: <InputAdornment position="start">{`FIL`}</InputAdornment>}}
```
Comment (BeroBurny) [inline packages/example/src/components/Transfer/Transfer.tsx:149]: There is no need JSX for static string

**Review by BeroBurny — APPROVED** [review]
LGTM

The comment is only for esthetical part of code
